name: build_umi_hyperos_OneDrivePush
on:
  workflow_dispatch:
    inputs:
      URL:
        description: "待操作的移植包下载地址"
        required: true
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        runs-on:
          - ubuntu-20.04
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@master
      - name: 1.准备环境
        run: |
          echo "date=$(echo ${{ github.event.inputs.URL }} | cut -d"/" -f4)" >> $GITHUB_ENV
              echo "device=umi" >> $GITHUB_ENV
              echo "ORIGN_ZIP_NAME=miui_UMI_V14.0.4.0.TJBCNXM_23fc5ef4ee_13.0.zip" >> $GITHUB_ENV
          sudo apt install python3 python3-pip aria2 zip p7zip-full tar zipalign zstd openjdk-8-jre
          sudo apt --fix-broken install
          sudo apt update --fix-missing
          pip3 install --upgrade pip
          pip3 install pycryptodome
          pip3 install setuptools
          pip3 install docopt
          pip3 install requests
          pip3 install beautifulsoup4
          pip3 install --ignore-installed pyyaml
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone/
          unzip "$GITHUB_WORKSPACE"/tools/rclone.zip -d ~/.config/rclone/
      - name: 2.克隆仓库&下载系统包
        run: |
          aria2c -x16 -j$(nproc) -U "Mozilla/5.0" -d "$GITHUB_WORKSPACE"  https://bigota.d.miui.com/V14.0.4.0.TJBCNXM/miui_UMI_V14.0.4.0.TJBCNXM_23fc5ef4ee_13.0.zip
          aria2c -x16 -j$(nproc) -U "Mozilla/5.0" -d "$GITHUB_WORKSPACE" ${{ github.event.inputs.URL }}
          if [[ ${{ github.events.inputs.url }} == *SHENNONG* ]];then 
            git clone --depth 1 https://github.com/toraidl/hyperos_port.git -b shennong-stable hyperos_port
          else
            git clone --depth 1 https://github.com/toraidl/hyperos_port.git -b fuxi-dev hyperos_port
          fi
      - name: 3. 开始移植
        run: |
          baserom="miui_UMI_V14.0.4.0.TJBCNXM_23fc5ef4ee_13.0.zip"
          portrom=$(basename ${{ github.event.inputs.URL }}
          cd hyperos_port
          sudo ./port $baserom $portrom
      - name: 4.上传到OneDrive
        run: |
            rclone mkdir onedrive:/MI_Packages/UMI_Packages
            rclone sync -P ./hyperos_port/out/*.zip onedrive:/MI_Packages/UMI_Packages
      - name: 5.删除工作流运行
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
